# Generated by Django 3.0.11 on 2021-02-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_computers.computer_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('computer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computers.Computer')),
                ('name', models.CharField(default='', max_length=200)),
                ('type', models.CharField(choices=[('Desktop', 'Desktop'), ('All-in-one', 'All-in-one')], max_length=200)),
                ('Brand', models.CharField(choices=[('Acer', 'Acer'), ('ASUS', 'ASUS'), ('HP', 'HP'), ('DELL', 'DELL'), ('MICROSOFT', 'MICROSOFT'), ('LENOVO', 'LENOVO')], default='', max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('computers.computer',),
        ),
        migrations.CreateModel(
            name='Portable',
            fields=[
                ('computer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computers.Computer')),
                ('name', models.CharField(default='', max_length=200)),
                ('type', models.CharField(choices=[('Laptop/Notenook', 'Laptop/Notenook'), ('2 in 1', '2 in 1'), ('Chromebook', 'Chromebook'), ('Microsoft Surface', 'Microsoft Surface')], max_length=200)),
                ('Brand', models.CharField(choices=[('Acer', 'Acer'), ('ASUS', 'ASUS'), ('HP', 'HP'), ('DELL', 'DELL'), ('MICROSOFT', 'MICROSOFT'), ('LENOVO', 'LENOVO')], default='', max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('computers.computer',),
        ),
    ]
