# Generated by Django 3.0.11 on 2021-02-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0004_auto_20210203_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portable',
            name='type',
            field=models.CharField(choices=[('Laptop/Notenook', 'Laptop/Notenook'), ('2 in 1', '2 in 1'), ('Chromebook', 'Chromebook'), ('Microsoft Surface', 'Microsoft Surface')], default='Laptop type', max_length=200),
        ),
    ]
