# Generated by Django 3.0.11 on 2021-02-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0005_auto_20210203_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portable',
            name='image',
        ),
        migrations.AddField(
            model_name='desktop',
            name='cpu',
            field=models.CharField(choices=[('Intel', (('core i9', 'core i9'), ('core i7', 'core i7'), ('core i5', 'core i5'), ('core i3', 'core i3'), ('other', 'other'))), ('AMD', (('Ryzen 7', 'Ryzen 7'), ('Ryzen 5', 'Ryzen 5'), ('Ryzen 3', 'Ryzen 3'), ('Other', 'Other')))], default='intel', max_length=200),
        ),
        migrations.AddField(
            model_name='desktop',
            name='series',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portable',
            name='cpu',
            field=models.CharField(choices=[('Intel', (('core i9', 'core i9'), ('core i7', 'core i7'), ('core i5', 'core i5'), ('core i3', 'core i3'), ('other', 'other'))), ('AMD', (('Ryzen 7', 'Ryzen 7'), ('Ryzen 5', 'Ryzen 5'), ('Ryzen 3', 'Ryzen 3'), ('Other', 'Other')))], default='intel', max_length=200),
        ),
        migrations.AddField(
            model_name='portable',
            name='series',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
