# Generated by Django 3.1.1 on 2021-04-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0008_auto_20210331_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
