# Generated by Django 3.1.1 on 2021-04-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0009_auto_20210401_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
