# Generated by Django 3.1.1 on 2021-04-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='hassan', max_length=100),
            preserve_default=False,
        ),
    ]
