# Generated by Django 3.2 on 2021-05-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0013_cpu_graphics_memory_os_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portable',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
