# Generated by Django 3.2 on 2021-05-11 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('computers', '0014_alter_portable_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='seller',
            field=models.ForeignKey(default='desktop', on_delete=django.db.models.deletion.CASCADE, related_name='desktops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portable',
            name='seller',
            field=models.ForeignKey(default='laptop', on_delete=django.db.models.deletion.CASCADE, related_name='portables', to=settings.AUTH_USER_MODEL),
        ),
    ]
