# Generated by Django 3.2 on 2021-05-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0016_alter_desktop_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='portable',
            name='seller',
        ),
    ]
