# Generated by Django 3.0.11 on 2021-02-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_components.component_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('type', models.CharField(choices=[('Intel', (('Core i9', 'Core i9'), ('Core i7', 'Core i7'), ('Core i5', 'Core i5'), ('Core i3', 'Core i3'), ('Celeron & Pentium', 'Celeron & Pentium'))), ('AMD', (('Threadripper', 'Threadripper'), ('Ryzen 9', 'Ryzen 9'), ('Ryzen 7', 'Ryzen 7'), ('Ryzen 5', 'Ryzen 5'), ('Ryzen 3', 'Ryzen 3')))], default='Intel', max_length=200)),
                ('brand', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], default='Intel', max_length=200)),
                ('processor_type', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop')], default='Desktop', max_length=200)),
                ('series', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(default='Core i9-10900K', max_length=200)),
                ('model', models.CharField(default='BX8070110900K', max_length=200)),
                ('cores', models.IntegerField(blank=True)),
                ('threads', models.IntegerField(blank=True)),
                ('memory_types', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR3', 'DDR3')], max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('components.component',),
        ),
    ]
