# Generated by Django 3.1.1 on 2021-04-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0010_auto_20210401_1014'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
