# Generated by Django 3.1.1 on 2021-04-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210406_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='Johndoe@gmail.com', max_length=250),
            preserve_default=False,
        ),
    ]
